import 'package:pelekapro_mobile/features/deliveries/demo/demo_delivery.dart';

const demoDeliveries = [
  DemoDelivery(
    id: 'demo-1',
    code: 'PP-24031',
    recipientName: 'Asha Juma',
    recipientPhone: '+255 712 345 678',
    pickupArea: 'Kariakoo, Dar es Salaam',
    pickupAddress: 'Uhuru Street, Kariakoo',
    dropoffArea: 'Mikocheni, Dar es Salaam',
    dropoffAddress: 'Mwai Kibaki Road, Mikocheni',
    scheduledTime: '10:00 AM',
    itemCount: 1,
    itemDescription: 'Documents',
    amountToCollect: 25000,
    paymentMethod: 'Cash on delivery',
    note: 'Call on arrival',
    status: DemoDeliveryStatus.assigned,
    lastUpdate: '9:15 AM',
    eta: '14 min',
    distance: '5.2 km',
  ),
  DemoDelivery(
    id: 'demo-2',
    code: 'PP-24032',
    recipientName: 'Neema Joseph',
    recipientPhone: '+255 754 210 987',
    pickupArea: 'Sinza, Dar es Salaam',
    pickupAddress: 'Shekilango Road, Sinza',
    dropoffArea: 'Oysterbay, Dar es Salaam',
    dropoffAddress: 'Haile Selassie Road, Oysterbay',
    scheduledTime: '12:30 PM',
    itemCount: 2,
    itemDescription: 'Parcels',
    amountToCollect: 18000,
    paymentMethod: 'Cash on delivery',
    note: 'Use the main entrance',
    status: DemoDeliveryStatus.onTheWay,
    lastUpdate: '12:05 PM',
    eta: '18 min',
    distance: '6.4 km',
  ),
  DemoDelivery(
    id: 'demo-3',
    code: 'PP-24033',
    recipientName: 'Baraka Mtei',
    recipientPhone: '+255 689 430 125',
    pickupArea: 'Ubungo, Dar es Salaam',
    pickupAddress: 'Morogoro Road, Ubungo',
    dropoffArea: 'Masaki, Dar es Salaam',
    dropoffAddress: 'Chole Road, Masaki',
    scheduledTime: '2:30 PM',
    itemCount: 1,
    itemDescription: 'Parcel',
    amountToCollect: 32000,
    paymentMethod: 'Cash on delivery',
    note: 'Ask for reception',
    status: DemoDeliveryStatus.arrived,
    lastUpdate: '2:28 PM',
    eta: 'Arrived',
    distance: '0 km',
  ),
  DemoDelivery(
    id: 'demo-4',
    code: 'PP-24034',
    recipientName: 'Rehema Kweka',
    recipientPhone: '+255 713 880 442',
    pickupArea: 'Mwenge, Dar es Salaam',
    pickupAddress: 'Sam Nujoma Road, Mwenge',
    dropoffArea: 'Kinondoni, Dar es Salaam',
    dropoffAddress: 'Kawawa Road, Kinondoni',
    scheduledTime: '4:45 PM',
    itemCount: 1,
    itemDescription: 'Documents',
    amountToCollect: 12000,
    paymentMethod: 'Cash on delivery',
    note: 'Delivered to the recipient',
    status: DemoDeliveryStatus.delivered,
    lastUpdate: '4:42 PM',
    eta: 'Completed',
    distance: '0 km',
  ),
  DemoDelivery(
    id: 'demo-5',
    code: 'PP-24035',
    recipientName: 'Zawadi Mbise',
    recipientPhone: '+255 765 330 214',
    pickupArea: 'Posta, Dar es Salaam',
    pickupAddress: 'Samora Avenue, Posta',
    dropoffArea: 'Ilala, Dar es Salaam',
    dropoffAddress: 'Nyerere Road, Ilala',
    scheduledTime: '5:30 PM',
    itemCount: 1,
    itemDescription: 'Parcel',
    amountToCollect: 15000,
    paymentMethod: 'Cash on delivery',
    note: 'Call on arrival',
    status: DemoDeliveryStatus.assigned,
    lastUpdate: '9:20 AM',
    eta: 'Pending start',
    distance: '4.8 km',
  ),
  DemoDelivery(
    id: 'demo-6',
    code: 'PP-24036',
    recipientName: 'Mariam Ally',
    recipientPhone: '+255 742 608 315',
    pickupArea: 'Masaki, Dar es Salaam',
    pickupAddress: 'Kimweri Avenue, Masaki',
    dropoffArea: 'Ubungo, Dar es Salaam',
    dropoffAddress: 'Nelson Mandela Road, Ubungo',
    scheduledTime: '6:15 PM',
    itemCount: 3,
    itemDescription: 'Parcels',
    amountToCollect: 40000,
    paymentMethod: 'Cash on delivery',
    note: 'Use the side entrance',
    status: DemoDeliveryStatus.assigned,
    lastUpdate: '9:25 AM',
    eta: 'Pending start',
    distance: '11.2 km',
  ),
];
